# Generated by Django 4.2.6 on 2023-10-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0002_alter_subject_capacity_alter_subject_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.PositiveIntegerField(),
        ),
    ]
